/**
 * Value Metrics Calculator
 *
 * Calculates ROI and value proposition for creators.
 * Shows what they GAINED from the referral program.
 */

import { prisma } from '../db/prisma';
import logger from '../logger';

export interface ValueMetrics {
  // Period
  periodStart: Date;
  periodEnd: Date;

  // Sales breakdown (leveraging existing memberOrigin field!)
  organicSalesCount: number;
  organicRevenue: number;
  referredSalesCount: number;
  referredRevenue: number;
  totalSalesCount: number;
  totalRevenue: number;

  // What creator keeps (new calculation)
  organicRevenueKept: number; // 100% of organic
  referredRevenueKept: number; // 70% of referred (they keep this)
  totalRevenueKept: number;

  // Value proposition (THE KEY METRICS)
  revenueWithoutApp: number; // Just organic (what they'd have without us)
  revenueWithApp: number; // Total after our revenue share
  additionalRevenueGenerated: number; // The gain from using our app
  percentageGrowth: number; // % increase

  // Platform fees
  platformFeesOwed: number; // 20% of referred sales
  platformFeeAsPercentOfGain: number; // What % of their GAIN we're taking
  netBenefit: number; // Their gain minus our fee
  roiOnPlatformFee: number; // How many X they make for every $1 they pay us

  // Additional context
  averageOrderValue: number;
  referralRate: number; // % of sales that are referred
  shouldInvoice: boolean; // True if fees > $10
}

/**
 * Calculate value metrics for a creator in a given period
 *
 * This shows:
 * - What revenue they had WITHOUT the referral program (organic only)
 * - What revenue they have WITH the referral program (organic + 70% of referred)
 * - The ADDITIONAL revenue generated by our app
 * - The ROI on the 20% platform fee
 */
export async function calculateValueMetrics(
  creatorId: string,
  periodStart: Date,
  periodEnd: Date
): Promise<ValueMetrics> {
  try {
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // STEP 1: Get all members for this creator in this period
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // We use memberOrigin to separate organic vs referred
    const members = await prisma.member.findMany({
      where: {
        creatorId,
        createdAt: {
          gte: periodStart,
          lte: periodEnd,
        },
      },
      select: {
        id: true,
        membershipId: true,
        memberOrigin: true, // "organic" | "referred"
      },
    });

    // Separate by origin
    const organicMembers = members.filter((m) => m.memberOrigin === 'organic');
    const referredMembers = members.filter((m) => m.memberOrigin === 'referred');

    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // STEP 2: Get all commissions (sales) for these members
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    const membershipIds = members.map((m) => m.membershipId);

    const allCommissions = await prisma.commission.findMany({
      where: {
        whopMembershipId: { in: membershipIds },
        status: 'paid',
        createdAt: {
          gte: periodStart,
          lte: periodEnd,
        },
      },
      select: {
        saleAmount: true,
        platformShare: true,
        whopMembershipId: true,
      },
    });

    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // STEP 3: Separate commissions by member origin
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    const organicMembershipIds = new Set(
      organicMembers.map((m) => m.membershipId)
    );
    const referredMembershipIds = new Set(
      referredMembers.map((m) => m.membershipId)
    );

    const organicCommissions = allCommissions.filter((c) =>
      organicMembershipIds.has(c.whopMembershipId)
    );
    const referredCommissions = allCommissions.filter((c) =>
      referredMembershipIds.has(c.whopMembershipId)
    );

    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // STEP 4: Calculate revenue totals
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    const organicRevenue = organicCommissions.reduce(
      (sum, c) => sum + Number(c.saleAmount),
      0
    );
    const referredRevenue = referredCommissions.reduce(
      (sum, c) => sum + Number(c.saleAmount),
      0
    );
    const totalRevenue = organicRevenue + referredRevenue;

    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // STEP 5: Calculate what creator keeps
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // Organic: Creator keeps 100% (no referral program involved)
    const organicRevenueKept = organicRevenue;

    // Referred: Creator keeps 70% (we take 20%, member gets 10%)
    const referredRevenueKept = referredRevenue * 0.7;

    const totalRevenueKept = organicRevenueKept + referredRevenueKept;

    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // STEP 6: Calculate value proposition
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // WITHOUT our app: they'd only have organic revenue
    const revenueWithoutApp = organicRevenue;

    // WITH our app: they have organic + 70% of referred
    const revenueWithApp = totalRevenueKept;

    // The ADDITIONAL revenue WE generated for them
    const additionalRevenueGenerated = revenueWithApp - revenueWithoutApp;

    // Percentage growth from using our app
    const percentageGrowth =
      revenueWithoutApp > 0
        ? (additionalRevenueGenerated / revenueWithoutApp) * 100
        : referredRevenue > 0
        ? 100 // If they had 0 organic but have referred, that's 100% growth
        : 0;

    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // STEP 7: Calculate platform fees (20% of referred sales)
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    const platformFeesOwed = referredCommissions.reduce(
      (sum, c) => sum + Number(c.platformShare),
      0
    );

    // What % of their GAIN are we taking?
    const platformFeeAsPercentOfGain =
      additionalRevenueGenerated > 0
        ? (platformFeesOwed / additionalRevenueGenerated) * 100
        : 0;

    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // STEP 8: Calculate ROI on our fee
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // How much value do they get for every $1 they pay us?
    const netBenefit = additionalRevenueGenerated - platformFeesOwed;
    const roiOnPlatformFee =
      platformFeesOwed > 0 ? additionalRevenueGenerated / platformFeesOwed : 0;

    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // STEP 9: Determine if should invoice
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    const MINIMUM_INVOICE_AMOUNT = 10;
    const shouldInvoice = platformFeesOwed >= MINIMUM_INVOICE_AMOUNT;

    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // STEP 10: Additional metrics
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    const totalSalesCount = allCommissions.length;
    const averageOrderValue =
      totalSalesCount > 0 ? totalRevenue / totalSalesCount : 0;

    const referralRate =
      totalSalesCount > 0
        ? (referredCommissions.length / totalSalesCount) * 100
        : 0;

    const metrics: ValueMetrics = {
      periodStart,
      periodEnd,
      organicSalesCount: organicCommissions.length,
      organicRevenue,
      referredSalesCount: referredCommissions.length,
      referredRevenue,
      totalSalesCount,
      totalRevenue,
      organicRevenueKept,
      referredRevenueKept,
      totalRevenueKept,
      revenueWithoutApp,
      revenueWithApp,
      additionalRevenueGenerated,
      percentageGrowth,
      platformFeesOwed,
      platformFeeAsPercentOfGain,
      netBenefit,
      roiOnPlatformFee,
      averageOrderValue,
      referralRate,
      shouldInvoice,
    };

    logger.info('✅ Value metrics calculated:', {
      creatorId,
      period: `${periodStart.toISOString().split('T')[0]} to ${
        periodEnd.toISOString().split('T')[0]
      }`,
      referredSales: referredCommissions.length,
      additionalRevenue: `$${additionalRevenueGenerated.toFixed(2)}`,
      platformFees: `$${platformFeesOwed.toFixed(2)}`,
      netBenefit: `$${netBenefit.toFixed(2)}`,
      roi: `${roiOnPlatformFee.toFixed(1)}x`,
      shouldInvoice,
    });

    return metrics;
  } catch (error) {
    logger.error('❌ Error calculating value metrics:', error);
    throw error;
  }
}
